--local ReturnBuffTracker                           = LibStub("AceAddon-3.0"):GetAddon("ReturnBuffTracker")
--local L                                           = LibStub("AceLocale-3.0"):GetLocale("ReturnBuffTracker")
--
--ReturnBuffTracker.Constants                       = {}
--
--ReturnBuffTracker.Constants.BarOptionGroups       = {
--    General    = L["General"],
--    Player     = L["Player buffs"],
--    World      = L["World"],
--    Consumable = L["Consumable"],
--    Misc       = L["Misc"],
--}
--
--ReturnBuffTracker.Constants.ReportChannel         = {
--    --"CHANNEL",
--    --"DND",
--    --"EMOTE",
--    ["GUILD"]         = L["Guild"],
--    ["INSTANCE_CHAT"] = L["Instance"],
--    ["OFFICER"]       = L["Officer"],
--    ["PARTY"]         = L["Party"],
--    ["RAID"]          = L["Raid"],
--    ["RAID_WARNING"]  = L["Raid Warning"],
--    ["SAY"]           = L["Say"],
--    --"WHISPER",
--    --"YELL"
--}

